### ISSUE TITLE
v0.1.0

### ISSUE THREAD

**Issue by seokhyun-oh** [ladybugproject/documents#1]
### 데이터 수집
- [x] [KOPIS 데이터 스키마 조사](https://github.com/ladybugproject/documents/issues/2)
- [ ] [KOPIS 데이터 수집](https://github.com/ladybugproject/documents/issues/5)
- [ ] [MySQL 스키마 생성](https://github.com/ladybugproject/documents/issues/3)
- [ ] [시/군/구 공통코드](https://github.com/ladybugproject/documents/issues/6)

### 추천 시스템
- [ ] [나이, 성별에 따른 공연 선호도 통계 찾기](https://github.com/ladybugproject/documents/issues/4)

### App
- [ ] [앱 마크업 제작 v0.1.0](https://github.com/ladybugproject/documents/issues/7)

**Comment by momentum1993** [comment]
#2 KOPIS 데이터 스키마 조사 완료
